export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_SUBCATEGORY = "ADD_SUBCATEGORY";
export const ADD_SUBPRODUCT = "ADD_SUBPRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const REMOVE_SUBCATEGORY = "REMOVE_SUBCATEGORY";
export const REMOVE_SUBPRODUCT = "REMOVE_SUBPRODUCT";
